#!/usr/bin/env ruby

require 'date'

POSTS_DIR = '_posts/'

post = ARGV[0]

if post.nil? || post.strip.empty?
  warn "Usage: #{$0} <post-name>"
  exit 1
end

filename = File.join(POSTS_DIR, Date.today.strftime('%Y-%m-%d-') + post + '.md')

File.open(filename, 'w') do |f|
  f.write <<~POST
    ---
    layout: post
    section-type: post
    title: Title
    category: Category
    tags: [ 'tag1', 'tag2' ]
    ---

  POST
end

puts "[+] Created #{filename}"
